# 公開リポジトリではCI回したくないのでコメントアウトしておく
# on:
#   schedule:
#     - cron: '0 0 * * *'
# jobs:
#   Deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Use Node.js
#         uses: actions/setup-node@v1
#         with:
#           node-version: '16.13.1'
#       - uses: actions/checkout@v2
#       - name: Get yarn cache directory path
#         id: yarn-cache-dir-path
#         run: echo "::set-output name=dir::$(yarn cache dir)"

#       - uses: actions/cache@v2
#         id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
#         with:
#           path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
#           key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
#           restore-keys: |
#             ${{ runner.os }}-yarn-
#       - name: Install dependencies
#         run: yarn --frozen-lockfile
#       - name: create secret json file
#         env:
#           JSON_FILE: ${{ secrets.JSON_FILE }}
#           TO_PATH: secret.json
#         run: echo $JSON_FILE > $TO_PATH

#       - name: create env file
#         env:
#           ENV_FILE: ${{ secrets.ENV_FILE }}
#           TO_PATH: .env
#         run: echo -e $ENV_FILE > $TO_PATH
#       - name: build
#         run: yarn run build
#       - name: exec
#         run: yarn run exec
